Adding week1 to the main
algosup/2023-2024-project-5-flutter-team-6 pull request #1
Opened 2024-05-19 10:59 UTC by CamilleGayat

2024-05-21 07:32 UTC, Pierre2103 submitted a review, later dismissed

2024-05-21 07:39 UTC, MathiasGagnepain requested changes
![](https://media0.giphy.com/media/6r8Yi0S7SUeqClWk9n/200w.gif?cid=6c09b952nioianl0lse92ce9vfk6sinbro94xyjzpjokb7is&ep=v1_gifs_search&rid=200w.gif&ct=g)

2024-05-21 07:39 UTC, MathiasGagnepain commented on documents/management/weekly_reports/week_1.md
> +- Gantt
You wrote "Finish" for others line but not form Gantt and RACI what will you do with these 2?

2024-05-21 07:39 UTC, MathiasGagnepain commented on documents/management/weekly_reports/week_1.md
> +- RACII
RACI not RACII

2024-05-21 08:04 UTC, Pierre2103 commented
line 6 - Use only dashes(-) or only fewer symbols(<) to allow consistency
line 8 - " The task didn't started yet " --> replace " didn't " by " haven't "
line 8 - " The task is at these beginnings and only the basis are made or are being made " --> " The ongoing task is still in progress and well started "
line 8 - " The task is progressing well and the team enter in the heart of it " --> " entering in the heart of it " OR " The task is progressing well and the task is coming to life. "
line 8 - " The end of the task approach and the team must continue at a good pace " --> " The task is coming to an end, however few changes has to be done. "
line 8 - " This is the last part of the task, finish the task and pass it in review. " --> " the final phase of the task has been completed and is currently being reviewed by the QA "
line 8 - " The task is entirely done and included " --> " The task is entirely completed and integrated in the repository "

2024-05-21 08:12 UTC, Pierre2103 commented
line 22 - " Github Repository creation " --> " Creation of the Github Repository "
line 26 - " A meeting was made " --> " A meeting was done "
line 27 - " Another one was made " --> " Another one was done "
line 27 - " 10 minutes before the end " --> " 10 minutes before the end of the day "
line 28 - " Two else were made " --> " Two more meetings were done "
line 28 - " at the beginning and the end of the project  " --> " at the start of the day and at the end of the day "
line 28 - " to share the progress and motivate the team "  --> " to maintain progression of the progression "

2024-05-21 08:27 UTC, Pierre2103 commented
line 32 - replace this:

> " This week the project advanced a lot, The decision to all make a different mock-up and then sharing them together to keep the best ideas of everyone was made, then with these ideas, 2 groups were made to prepare two mock-ups to present to the client. But we need to be careful about the deadline for the Functional specifications. "

by this :

> " The kick-off of the project was fairly satisfying, we decided as a team to come up with different mock-ups which we will present to the client.  Two main mock-ups has been keeped, and will be sent next week to the client."

line 34 - replace this:

> " Globally, all the members of the team worked a lot and brought of their own in the advancement. They are motivated and feels great, some are confident with flutter and dart. "

by this :

> " Globally, all team members has contributing to allow the team to come up with theses final mock-ups, the team members motivation is on-point and few team members feels confident with Dart and Flutter technologies. "

line 38 to line 45 - replace everything by 

> " The next weeks main concern will be focus on the Functional Specifications, and in parallel completing the Project Charter, Wait for the response of the client, finishing the GANTT Charter and finishing the RACI Matrix "

2024-05-21 08:42 UTC, MathiasGagnepain approved these changes, later dismissed
![](https://media1.giphy.com/media/VR5IdPPi93MSWQD51e/200w.gif?cid=6c09b952nsmsuwvwdpey85ts8384ty2399vukhh3rcxqe5tc&ep=v1_gifs_search&rid=200w.gif&ct=g)

2024-05-22 15:40 UTC, MathiasGagnepain requested changes
![](https://media0.giphy.com/media/l4pTocra1lFDomV5S/200w.gif?cid=6c09b952bvq1xxf4j1515w9147ak7d08enqthovi9nb1whbr&ep=v1_gifs_search&rid=200w.gif&ct=g)

2024-05-22 15:40 UTC, MathiasGagnepain commented on documents/management/project_charter.md
> +| **Name** | **Role** | **Represented by** | **Contact** |
don't forget to remove contact column

2024-05-22 15:42 UTC, MathiasGagnepain commented
@Pierre2103 @CamilleGayat don't forget to complete the review of the pull request.
If not completed I will close the PR tomorrow at the end of the day.

2024-05-23 11:40 UTC, Pierre2103 commented
Perfect !

2024-05-23 11:43 UTC, Pierre2103 approved these changes

2024-05-23 11:43 UTC, Pierre2103 approved these changes

2024-05-23 11:44 UTC, MathiasGagnepain approved these changes
![](https://media4.giphy.com/media/j2GPljpvL8Lulm3d0X/200w.gif?cid=6c09b952z7ka2rkm8lue2827so864mirhji3nbvrgwge3w55&ep=v1_gifs_search&rid=200w.gif&ct=g)

2024-05-23 11:44 UTC, merged